//***********************************************************************
//*                                                                     *
//*   Copyright (c) 1985-2019, American Megatrends International LLC.   *
//*                                                                     *
//*      All rights reserved. Subject to AMI licensing agreement.       *
//*                                                                     *
//***********************************************************************
/** @file
  AmiPlatformDriverOverrideHooks.h is generated by AMISDL from AmiNvramPeiPlatformHooksTemplate.h
  This header file defines Platform Driver Override platform hooks.
  AMISDL replaces @@elink commands below with the content of the corresponding eLink.

  Do not include this header in your source file. It is a private header of the BDS module.
**/
#define HOOK_GET_DRIVER_PARAMS\
  IN EFI_PLATFORM_DRIVER_OVERRIDE_PROTOCOL              *This,\
  IN     EFI_HANDLE                                     ControllerHandle,\
  IN OUT EFI_HANDLE                                     *DriverImageHandle


typedef EFI_STATUS (EFI_PLATFORM_DRIVER_OVERRIDE_ELINK_FUNCTION)(HOOK_GET_DRIVER_PARAMS );


/* ************************************************************************************* */
// Platform Driver Override functions eLink
/* ************************************************************************************* */
@elink(PLATFORM_DRIVER_OVERRIDE_FUNCTIONS,
"EFI_STATUS @replace(@child,@token(BDS_SDL_TEMPLATE_COMMA),@token(NON_EXISTENT_TOKEN))(HOOK_GET_DRIVER_PARAMS );", "%n" ,"")



//#define PLATFORM_DRIVER_OVERRIDE_FUNCITON_LIST @elink(PLATFORM_DRIVER_OVERRIDE_FUNCTIONS, "@Child"," " ,"" )

EFI_PLATFORM_DRIVER_OVERRIDE_ELINK_FUNCTION *PlatformDriverOverrideFunctions[] = {
@elink(PLATFORM_DRIVER_OVERRIDE_FUNCTIONS,
"    @child,", "%n" ,"%n    NULL")
};
