//***********************************************************************
//*                                                                     *
//*   Copyright (c) 1985-2019, American Megatrends International LLC.   *
//*                                                                     *
//*      All rights reserved. Subject to AMI licensing agreement.       *
//*                                                                     *
//***********************************************************************

/** @file
  AuthVariableHooks.h is generated by AMISDL from AuthVariableHooksTemplate.h
  This header file defines AuthVar service hooks.
  AMISDL replaces @@elink commands below with the content of the corresponding eLink.
  
  Do not include this header in your source file. It is a private header of the AutService module.
**/

/* ************************************************************************************* */
// elink API hooks
/* ************************************************************************************* */
typedef BOOLEAN (AUTHVAR_PHYSICAL_USER_OVERRIDE)( VOID );

@elink(AuthVariablePhysicalUserOverride,
"BOOLEAN @replace(@child,@token(AUTHVAR_HOOK_LIB_COMMA),@token(NON_EXISTENT_TOKEN))(VOID);", "%n" ,"")

AUTHVAR_PHYSICAL_USER_OVERRIDE *AuthVariablePhysicalUserOverrideList[] = {
@elink(AuthVariablePhysicalUserOverride,
"    @replace(@child,@token(AUTHVAR_HOOK_LIB_COMMA),@token(NON_EXISTENT_TOKEN)),", "%n" ,"%n    NULL")
};
