//**********************************************************************
//**********************************************************************
//**                                                                  **
//**        (C)Copyright 1985-2017, American Megatrends, Inc.         **
//**                                                                  **
//**                       All Rights Reserved.                       **
//**                                                                  **
//**             5555 Oakbrook Pkwy, Norcross, GA 30093               **
//**                                                                  **
//**                       Phone: (770)-246-8600                      **
//**                                                                  **
//**********************************************************************
//**********************************************************************
/** @file
  AmiTpm12PeiPlatformHooks.h is generated by AMISDL from AmiTpm12PeiPlatformHooksTemplate.h
  This header file defines Tpm12SkipInitialization hooks.
  AMISDL replaces @@elink commands below with the content of the corresponding eLink.
  
  Do not include this header in your source file. It is a private header of TCG2 module.
**/

/* ************************************************************************************* */
// elink API hooks
/* ************************************************************************************* */
typedef BOOLEAN (SKIP_TPM12_INITIALIZATION_HOOK_OVERRIDE)( VOID );

@elink(SkipTpm12InitializationHook,
"BOOLEAN @replace(@child,@token(TPM_HOOK_LIB_COMMA),@token(NON_EXISTENT_TOKEN))(VOID);", "%n" ,"")

SKIP_TPM12_INITIALIZATION_HOOK_OVERRIDE *SkipTpm12InitializationHookList[] = {
@elink(SkipTpm12InitializationHook,
"    @replace(@child,@token(TPM_HOOK_LIB_COMMA),@token(NON_EXISTENT_TOKEN)),", "%n" ,"%n    NULL")
};

//**********************************************************************
//**********************************************************************
//**                                                                  **
//**        (C)Copyright 1985-2017, American Megatrends, Inc.         **
//**                                                                  **
//**                       All Rights Reserved.                       **
//**                                                                  **
//**             5555 Oakbrook Pkwy, Norcross, GA 30093               **
//**                                                                  **
//**                       Phone: (770)-246-8600                      **
//**                                                                  **
//**********************************************************************
//**********************************************************************
